### ISSUE TITLE
LCZ-based urban simulation

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#3]
Hi all,

As a reminder, we planned to do three WRF runs with a domain centered over Kuala Lumpur:
1. **Natural**: urban areas replaced by its surrounding natural land cover (RUNNING)
2. **Default Urban**: WRF's default urban extent is replaced by the LCZ-based urban extent. Urban in this case is still binary.
3. **LCZ-based Urban**: using the LCZ classes and urban canopy parameters to describe the intra-urban heterogeneity.

This issues is about the **LCZ-based Urban** simulation.

This is how I understand the procedure, which consists out of two parts. @andreazonato, can you please check this and let me know if something is wrong?

**PART I**

The original LCZ map (100 m resolution) is converted to the parameters MH_URB2D, STDH_URB2D and LF_URB2D, and these are aggregated and added to the geo_em.d02.nc file.

@andreazonato: correct?

**PART II**
The original LCZ map (100 m resolution) is resampled to WRF grid using the majority filter, and then a .txt file needs to be creates with columns for x and y index and LCZ class.

@andreazonato: can you explain here how this .txt file needs to be created?

Some more questions @dargueso :

* I noticed URBPARM_LCZ.TBL contains 11 classes, with class 11 = asphalt. Is this LCZ 15 (which can also be natural rocks?). In my script, I currently do not consider LCZ 15 as an urban class.
* This TBL file also contains values for Building height (and its standard deviation). Are these not taken from PART I then?

To be honest, I thought that this new WRF release would really be able to ingest LCZ information by default. Which I interpreted as as user would need to only provide the high-res LCZ map in a directory, and the pre-processor would do the rest.

But it seems this is not the case at all? So perhaps it would also be helpful for me, if you @andreazonato, could remind me why this new version of WRF is different from the original WUDAPT-TO-WRF routine? As it still involves quite a bit of manual steps?

Ideally I would like to come up with one universal patch, that allows a user to create all required information with one script .... instead of having to look for bits and pieces at places?

**Comment by andreazonato** [comment]
@matthiasdemuzere 
PART I is correct. The values you are referring to are taken from the binary files in WPS, and interpolated into the geo_em.* Is should be done with the rd_wr_binary.f90 I passed you that should be opportunely modified, in order to give to the nx x ny x 132 URBPARAM matrix the correct verical coordinate.

PART II
The file should be created in which way you want. The first column is the cell number of x, the second the cell number of y and the third the LCZ. You should  have even the horizontal resolution in lat lon, the number of points in the two directions and the coordinate of the south-west corner, to be given in the "index" text file, so WPS can locate it.

Answering to your other questions:
_"I noticed URBPARM_LCZ.TBL contains 11 classes, with class 11 = asphalt. Is this LCZ 15 (which can also be natural rocks?). In my script, I currently do not consider LCZ 15 as an urban class."_
Exactly, i called LCZ 15 as LCZ 11, assigning it to an urban class, so we can describe correctly large asphalt areas such as airport lanes and big car parks.

_"This TBL file also contains values for Building height (and its standard deviation). Are these not taken from PART I then?"_
If you assign an input file, such as the ones you are created, these lookup parameters are not read, since you are giving them in input.

_"But it seems this is not the case at all? So perhaps it would also be helpful for me, if you @andreazonato, could remind me why this new version of WRF is different from the original WUDAPT-TO-WRF routine? As it still involves quite a bit of manual steps?"_
There are no differences with respect to the original WUDAPT-TO-WRF. The only difference is that the WRF code has been already modified, and there is no need to hard-code it to make it suitable with LCZ. Is is simply a matter of turning on a flag.

Hope I've been clear.

**Comment by matthiasdemuzere** [comment]
> PART I is correct. The values you are referring to are taken from the binary files in WPS, and interpolated into the geo_em.* Is should be done with the rd_wr_binary.f90 I passed you that should be opportunely modified, in order to give to the nx x ny x 132 URBPARAM matrix the correct verical coordinate.

Unfortunately I am not so familiar wth WRF's WPS system. But since I am developing all of this in python, I could basically mimic this procedure in python, no?  

@andreazonato: Perhaps you could provide me with one of your processed geo_em file that already contains these variables? So that I know what I should be working towards?
> 
> PART II
> The file should be created in which way you want. The first column is the cell number of x, the second the cell number of y and the third the LCZ. You should have even the horizontal resolution in lat lon, the number of points in the two directions and the coordinate of the south-west corner, to be given in the "index" text file, so WPS can locate it.

Mmm... ok. So also this one I will try to create in python then. Also here, do you @andreazonato  have an example of how the file should look? Probably best if it corresponds to the geo_em file you sent, so that I can figure out e.g. in which corner this list starts, how the index is created etc ...

> 
> Answering to your other questions:
> _"I noticed URBPARM_LCZ.TBL contains 11 classes, with class 11 = asphalt. Is this LCZ 15 (which can also be natural rocks?). In my script, I currently do not consider LCZ 15 as an urban class."_
> Exactly, i called LCZ 15 as LCZ 11, assigning it to an urban class, so we can describe correctly large asphalt areas such as airport lanes and big car parks.

This I understand. But LCZ 15 also represents bare rock. So in case your model domain is over the high Alps, all bare rock slopes would be described as asphalt. Which of course is wrong. LCZ 15 is a very ambiguous class from a model perspective, I am also not sure how this should be best handled. 
> 
> _"This TBL file also contains values for Building height (and its standard deviation). Are these not taken from PART I then?"_
> If you assign an input file, such as the ones you are created, these lookup parameters are not read, since you are giving them in input.

Ok, clear. 

Does this also mean that, if more params are defined via the geo em file, these will also not be read from the .txt file?
> 
> _"But it seems this is not the case at all? So perhaps it would also be helpful for me, if you @andreazonato, could remind me why this new version of WRF is different from the original WUDAPT-TO-WRF routine? As it still involves quite a bit of manual steps?"_
> There are no differences with respect to the original WUDAPT-TO-WRF. The only difference is that the WRF code has been already modified, and there is no need to hard-code it to make it suitable with LCZ. Is is simply a matter of turning on a flag.
> 

Ha, ok. So the "default" refers to the internal model code, that allows a user to easily switch to LCZ-based parameters via a flag. Yet it does not refer to the pre-processing, that is needed to prepare the appropriate input files.

If my reasoning is correct, it still might be valuable to create this python routine that allows a user to create all required input, in a manner that might be more straightforward than how it currently is using the fortran routines? 

Although I am not sure about this, as I never used the fortran routines. But my feeling tells me it could be made more simpler for inexperienced users.

> Hope I've been clear.

Yes, sure! These conversations are useful to improve my understanding ...

**Comment by andreazonato** [comment]
@matthiasdemuzere,
All the examples of the files are included into the WUDAPT_TO_WRF folder in the code section. To make the things easier, should we plan a call togheter so I can say you where to look at as example?

**Comment by matthiasdemuzere** [comment]
@andreazonato 

Mmm ... I have been looking into this folder, but I was not really seeing the files I was expecting. 
So yes, good idea to have a call. 

Would you be available this afternoon already?

**Comment by andreazonato** [comment]
@matthiasdemuzere  What about 4 pm?

**Comment by matthiasdemuzere** [comment]
Ha, that will not work for me.
Otherwise we can do it tomorrow before noon?
Anything after 9h15 works for me.

**Comment by andreazonato** [comment]
Ok, that works for me too. Let's do at 9:30?

**Comment by dargueso** [comment]
Sorry guys, I've been very busy teaching since Monday. I can't today, but could tomorrow. I also have teaching tomorrow, so I would only have a couple of spare hours between 9.30am and 11.30am. While I was writing I got your messages. 9.30am tomorrow is fine with me too.
I'll go through your messages this afternoon and reply if I need to.

**Comment by matthiasdemuzere** [comment]
Great. See zoom invite in inbox!
