### ISSUE TITLE
GREENFRAC

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#8]
> Hi, I've run the python code and it runs smoothly in a fresh python environment. I just had to install a few modules. So this is perfect!
I've noticed that GREENFRAC is exactly the same in both geo_em.d02_NoUrban.nc and geo_em.d02.nc. This is because in my script original script, the part where GREENFRAC is modified was commented. Unfortunately, I didn't uncommented it and experiment A is running with the original GREENFRAC. For consistency and given that the simulations past half way, we cannot change it now, but it something that should be changed for the tool we will make available. Hope that doesn't make a significant effect. I will check the model outputs to see if I can detect a signal in near-surface variables (temperature and humidity).

Just opening a dedicated issue to GREENFRAC, I have the feeling we might have to talk about this one a bit more?

**Comment by dargueso** [comment]
I agree. I have been thinking about this in the last couple of days. My idea is that in many cases, it will be impossible to restore GREENFRAC to its natural value, because it is impossible to determine what the natural value is. For example, in most European cities, which we're more familiar with, the surroundings are already altered by humans, although that is not scrictly urbanisation. There is no clear and objective way to restore the city to the original landscape. Plus, the question is what the original landscape actually is. So the safest approach is to remove the city and set all parameters to the surroundings, including GREENFRAC, which is the reference we normally use to define the UHI. This will lead to GREENFRAC values that are affected by humans, such as our case in Kuala Lumpur, but similarly to other cities. 

My experience with Sydney: the attempts to define the pre-European landscape at each location and replace the urban areas with it was extremely hard and involved many ad hoc decisions. I can't think of a way to objectively and generically export this to other cities.

**Comment by matthiasdemuzere** [comment]
I'd like to take a step back, for my understanding:

In case a pixel is urban (LU_INDEX == 13 or an LCZ number), and LANDUSEF Urban == 1. Then:
- GREENFRAC is not used, correct?

In that case, how is the vegetated part of that urban pixel treated? Example for LCZ 2, where URB_FRAC = 0.9, which leaves 0.1 of that cell non-urban. How is this treated?

In case GREENFRAC is not used for urban pixels, then it is only relevant for:
- the experiment where urban is removed (our exp. A)
- or for pixels that were urban from MODIS, but converted to non-urban after applying the LCZ urban extent.

For this case, it agree it is impossible to come up with an objective and generic approach to set GREENFRAC to an original natural state. 

We had a similar issue for the COSMO-to-WUDAPT conversion tool. In there, I approached this by (see [here](https://github.com/matthiasdemuzere/WUDAPT-to-COSMO/blob/48273c5de2d7fe0da4cce16f4ee9c8efbf779da4/utils.py#L391)):
- sampling values from the full non-urban/water domain
- make a distribution out of those
- random sample values within the 1st and 3rd quantile range
- and put these random values into grid cells that need to be adjusted.

It is clear that also this approach makes quite a number of assumptions. 
The advantage to just taking the mean (and thus have GREENFRAC the same for all urban pixels) is that there is more variability in space ...

**Comment by dargueso** [comment]
As far as I understand, GREENFRAC is used for the non-urban portion of the cell. 

The model outcome for a urban cell is a weighted average using URB_FRAC. SLUCM (or other UCM, I guess) passes information to NOAH-LSM and the PBL scheme. Both NOAH-LSM and PBL provide two solutions (urban and non-urban, based on the information passed on by the UC) and compute the weighted average based on URB_FRAC. I don't remember the exact details about the underlying information on vegetation, etc, that the LSM and PBL use to describe the non-urban portion. I'd had to read the code again.

In any case, for most urban cells, the effect of GREENFRAC differences will be very small, since contributions from GREENFRAC changes (20% in our case) will be multiplied by 0.1 in a urban landscape with URB_FRAC of 0.9.

**Comment by matthiasdemuzere** [comment]
Mmm ... interesting.

So in our case of 90% urban and 10% non-urban:

- if GREENFRAC is eg. 50% for that cell, then only 5% of the full grid cell is considered covered by a green fraction (whatever that may be ... grass, trees, ...)?
-  so what is the 5% remaining cover then? 

Sorry for all these questions, I am just trying to understand WRF and its LSMs better ....

**Comment by dargueso** [comment]
This is part of how NOAH-LSM deals with vegetation cover. The portion that is not vegetated is treated as bare, using soil properties, which depend on the soil type and soil state, to compute the fluxes.
